# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World JAYASHREE'
        required: true
      MAJOR:
        description: 'Major'
        required: true
        default: 1.0
      MINOR:
        description: 'Minor'
        required: true
        default: 0.0 
      Branch:
        description: 'Branch'
        required: true
      ReleaseVersion:
        description: 'Release Version'
        required: true

jobs:

  greet_and_generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}        
      - name: Print new build number
        run: echo "Generated Build Number-$BUILD_NUMBER"
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m')"
      - name: Get Version NUmber
        run: echo "The Current Build number NEW format for SWAN-${{ steps.date.outputs.date }}.$BUILD_NUMBER"	
  Checkout:
    # To Checkout the code
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: X021740/Laxmi.git
          ref: ${{ github.event.inputs.Branch }}
          token: ${{secrets.github_token}}
          path: X021740/Laxmi.git 
